name: Build Chromium

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  build-chromium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Chromium
      uses: actions/checkout@v3
      with:
        repository: 'chromium/chromium'
        path: 'chromium'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build git python3-dev python3-pip

    - name: Fetch Depot Tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH=$PATH:$(pwd)/depot_tools

    - name: Sync and Configure
      working-directory: ./chromium
      run: |
        gclient sync
        gn gen out/Default --args='is_debug=false'

    - name: Build Chromium
      working-directory: ./chromium
      run: |
        ninja -C out/Default chrome

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Chromium Binary
        path: ./chromium/out/Default/chrome
